#!/bin/sh

set -eu

lb config noauto \
    --mode debian \
    --distribution trixie \
    --architectures amd64 \
    --binary-image iso-hybrid \
    --archive-areas "main contrib non-free non-free-firmware" \
    --apt-recommends true \
    --image-name "moegi-os-debian" \
    --iso-application "Moegi OS Debian Edition" \
    --iso-publisher "Moegi OS Project" \
    --iso-volume "MOEGI_OS" \
    --bootappend-live "boot=live components locales=ja_JP.UTF-8 timezone=Asia/Tokyo keyboard-layouts=jp username=moegi hostname=moegi"
