---
modules-search: [ local ]

branding: moegi

prompt-install: false

sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary

  - exec:
      - partition
      - mount
      - unpackfs
      - machineid
      - fstab
      - locale
      - keyboard
      - localecfg
      - users
      - displaymanager
      - networkcfg
      - hwclock
      - services-systemd
      - initramfs
      - grubcfg
      - bootloader

  - show:
      - finished
