---
defaultGroups:
    - cdrom
    - floppy
    - sudo
    - audio
    - dip
    - video
    - plugdev
    - netdev
    - bluetooth
    - lpadmin
    - scanner

autologinGroup: autologin

doAutologin: false

setRootPassword: false

allowWeakPasswords: false

allowWeakUsernames: false

userShell: /bin/bash

hostname:
    location: User
    template: moegi
